"""add_category_heading_to_tax_return_transaction

Revision ID: 0f918a9a85ab
Revises: f0dda6e753db
Create Date: 2025-09-13 10:13:12.234676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f918a9a85ab'
down_revision = 'f0dda6e753db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_return_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_heading', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_return_transaction', schema=None) as batch_op:
        batch_op.drop_column('category_heading')

    # ### end Alembic commands ###
