"""Rename airbnb_listing_id to listing_id for multi-platform support

Revision ID: 1f93d4586636
Revises: b13fa9d1a3b2
Create Date: 2025-09-10 13:41:28.135628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f93d4586636'
down_revision = 'b13fa9d1a3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airbnb_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.String(length=50), nullable=False))
        batch_op.drop_column('airbnb_listing_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airbnb_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('airbnb_listing_id', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('listing_id')

    # ### end Alembic commands ###
