"""add_bank_api_fields_to_business_account

Revision ID: 207256e4b99b
Revises: 5bd0bc206a48
Create Date: 2025-09-10 08:49:57.751137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207256e4b99b'
down_revision = '5bd0bc206a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('api_credentials', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_refreshed', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_account', schema=None) as batch_op:
        batch_op.drop_column('last_refreshed')
        batch_op.drop_column('api_credentials')
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
