"""Add overpayment and ERC fields to Loan model

Revision ID: 2f00557b0730
Revises: 38ab1e8bf5c8
Create Date: 2025-09-10 00:16:34.530968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f00557b0730'
down_revision = '38ab1e8bf5c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regular_overpayment', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('overpayment_start_month', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('overpayment_end_month', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('erc_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('erc_end_date', sa.Date(), nullable=True))

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_person_family_id', 'family', ['family_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint('fk_person_family_id', type_='foreignkey')

    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_column('erc_end_date')
        batch_op.drop_column('erc_rate')
        batch_op.drop_column('overpayment_end_month')
        batch_op.drop_column('overpayment_start_month')
        batch_op.drop_column('regular_overpayment')

    # ### end Alembic commands ###
