"""add_max_extra_payment_field_to_loan

Revision ID: 5bd0bc206a48
Revises: a2c1d18e96a6
Create Date: 2025-09-10 08:02:05.628454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd0bc206a48'
down_revision = 'a2c1d18e96a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_extra_payment', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_column('max_extra_payment')

    # ### end Alembic commands ###
