"""add_pension_table

Revision ID: 8e016c636cec
Revises: c6e22e74a983
Create Date: 2025-09-10 01:02:55.512269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e016c636cec'
down_revision = 'c6e22e74a983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('pension_type', sa.String(length=50), nullable=False),
    sa.Column('contribution_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contribution_frequency', sa.String(length=20), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('is_company_contribution', sa.Boolean(), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('pension_provider', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pension')
    # ### end Alembic commands ###
