"""Add detailed fields to AirbnbBooking model

Revision ID: 91b614a4fdd4
Revises: 86ae2c044354
Create Date: 2025-09-10 13:30:18.602796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b614a4fdd4'
down_revision = '86ae2c044354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airbnb_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dtstamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('confirmation_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('guest_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('guest_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('guest_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('number_of_guests', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nightly_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cleaning_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('service_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('booking_source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cancellation_policy', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('special_requests', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airbnb_booking', schema=None) as batch_op:
        batch_op.drop_column('special_requests')
        batch_op.drop_column('cancellation_policy')
        batch_op.drop_column('booking_source')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('service_fee')
        batch_op.drop_column('cleaning_fee')
        batch_op.drop_column('nightly_rate')
        batch_op.drop_column('number_of_guests')
        batch_op.drop_column('guest_email')
        batch_op.drop_column('guest_phone')
        batch_op.drop_column('guest_name')
        batch_op.drop_column('confirmation_code')
        batch_op.drop_column('dtstamp')
        batch_op.drop_column('description')
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
