"""Add additional iCal fields to AirbnbBooking

Revision ID: b13fa9d1a3b2
Revises: 91b614a4fdd4
Create Date: 2025-09-10 13:36:34.135492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13fa9d1a3b2'
down_revision = '91b614a4fdd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airbnb_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('organizer', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('attendee', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airbnb_booking', schema=None) as batch_op:
        batch_op.drop_column('last_modified')
        batch_op.drop_column('created')
        batch_op.drop_column('attendee')
        batch_op.drop_column('organizer')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
