"""Add income_category field to Income model

Revision ID: c6e22e74a983
Revises: 2f00557b0730
Create Date: 2025-09-10 00:24:24.287296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e22e74a983'
down_revision = '2f00557b0730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('income_category', sa.String(length=50), nullable=True, default='non_rental'))
    
    # Update existing records to have default value
    op.execute("UPDATE income SET income_category = 'non_rental' WHERE income_category IS NULL")
    
    # Now make the column NOT NULL
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('income_category', nullable=False)

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_person_family_id', 'family', ['family_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint('fk_person_family_id', type_='foreignkey')

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('income_category')

    # ### end Alembic commands ###
