"""Add currency field to loan table

Revision ID: efcff6d747a8
Revises: 0f918a9a85ab
Create Date: 2025-09-17 16:13:37.188658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efcff6d747a8'
down_revision = '0f918a9a85ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))

    with op.batch_alter_table('tax_return_transaction', schema=None) as batch_op:
        batch_op.alter_column('category_heading',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_return_transaction', schema=None) as batch_op:
        batch_op.alter_column('category_heading',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
