"""Add file storage fields to BusinessAccount model

Revision ID: f0dda6e753db
Revises: d67688fb5919
Create Date: 2025-09-12 14:31:28.959534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0dda6e753db'
down_revision = 'd67688fb5919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_airbnb_booking')
    with op.batch_alter_table('airbnb_booking', schema=None) as batch_op:
        batch_op.alter_column('listing_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('business_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_imported_file_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_imported_file_content', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('last_imported_file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_imported_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_account', schema=None) as batch_op:
        batch_op.drop_column('last_imported_at')
        batch_op.drop_column('last_imported_file_size')
        batch_op.drop_column('last_imported_file_content')
        batch_op.drop_column('last_imported_file_name')

    with op.batch_alter_table('airbnb_booking', schema=None) as batch_op:
        batch_op.alter_column('listing_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    op.create_table('_alembic_tmp_airbnb_booking',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('property_id', sa.INTEGER(), nullable=True),
    sa.Column('booking_uid', sa.VARCHAR(length=200), nullable=False),
    sa.Column('reservation_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('phone_last_4', sa.VARCHAR(length=4), nullable=True),
    sa.Column('check_in_date', sa.DATE(), nullable=False),
    sa.Column('check_out_date', sa.DATE(), nullable=False),
    sa.Column('nights', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('estimated_income', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_synced', sa.DATETIME(), nullable=True),
    sa.Column('summary', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('dtstamp', sa.DATETIME(), nullable=True),
    sa.Column('confirmation_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('guest_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('guest_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('guest_email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('number_of_guests', sa.INTEGER(), nullable=True),
    sa.Column('nightly_rate', sa.FLOAT(), nullable=True),
    sa.Column('cleaning_fee', sa.FLOAT(), nullable=True),
    sa.Column('service_fee', sa.FLOAT(), nullable=True),
    sa.Column('total_amount', sa.FLOAT(), nullable=True),
    sa.Column('booking_source', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cancellation_policy', sa.VARCHAR(length=50), nullable=True),
    sa.Column('special_requests', sa.TEXT(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), nullable=True),
    sa.Column('organizer', sa.VARCHAR(length=200), nullable=True),
    sa.Column('attendee', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('last_modified', sa.DATETIME(), nullable=True),
    sa.Column('listing_id', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_uid')
    )
    # ### end Alembic commands ###
