"""add_loan_erc_table_and_remove_old_erc_fields

Revision ID: fd616c509678
Revises: 8e016c636cec
Create Date: 2025-09-10 01:34:19.427888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd616c509678'
down_revision = '8e016c636cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_erc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('erc_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_column('erc_rate')
        batch_op.drop_column('erc_end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('erc_end_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('erc_rate', sa.FLOAT(), nullable=True))

    op.drop_table('loan_erc')
    # ### end Alembic commands ###
